---
# tasks file for CREATE-EC2
#
#
- name : "read the env"
  include_vars : 
   file : "vars/{{ PROJECT }}_{{ ENV }}.yml"

- ec2:
    region: "{{ REGION }}"
    key_name: "{{ KEYNAME }}"
    instance_type: t2.micro
    image: "{{ IMAGE }}"
    wait: yes
    group: "{{ SGROUP }}"
    vpc_subnet_id: "{{ SUBID }}"
    assign_public_ip: yes
